;-------------------------------;
; Copyright (C) 1999 IDK, Inc.  ;
;     http://www.idk-inc.com    ;
;   Virtual Language Msg File   ;
;   ~nokeywords~                ;
;-------------------------------;
000001 '?)yna fi( segnahc ruoy lla esol ot tnaw uoy erus uoy erA'
000002 '2/gniRyeK'
000003 'segnahc esabatad evaS'
000004 '2/gniRyeK no pleh teG'
000005 '2/gniRyeK esolC'
000006 'nmuloc drowssap ediH'
000007 'yrtne LRU tnerruc no resworb nepO'
000008 'sgnitteS 2/gniRyeK egnahC'
000009 'esabatad drowssap etaerC/nepO'
000010 '54'
000011 '.evitca noitasrevnoc oN'
000012 'eliF~'
000013 'nepO~'
000014 'esabatad drowssap wen a nepO'
000015 'evaS~'
000016 'esabatad tnerruc eht evaS'
000017 'sA~ evaS'
000018 'eman wen a rednu esabatad tnerruc eht evaS'
000019 'put~eS'
000020 'elif txet detpyrcnenu na sa esabatad eht evaS'
000021 'tropxE~'
000022 'tnirP~'
000023 'sdrowssap dna seirtne esabatad lla tnirp'
000024 '-'
000025 'tix~E'
000026 '2/gniRyeK tiuQ'
000027 'pleH~'
000028 'xednI~ pleH'
000029 'scipot 2/gniRyeK no stnetnoc fo elbat weiV'
000030 'pleH lareneG~'
000031 'scipot noitacilppa 2/SO lareneg no pleh weiV'
000032 'pleH gnisU~'
000033 'metsys pleh eht esu ot woh no noitamrofni weiV'
000034 'pleh syeK~'
000035 'snoitca esuom dna syektoh no pleh weiV'
000036 'pleH 2gnir~yeK'
000037 'pleh lareneg 2/gniRyeK weiV'
000038 'noitamrofnI tcudorP~'
000039 'noitartsiger dna noisrev tcudorp weiV'
000040 'uneMremiT'
000041 'remiT lliK'
000042 'sedoc noitartsiger dna sdrowssap noitacilppA'
000043 'sedoC noitacilppA'
000044 'sdrowssap deripxe rof esabatad kcehC'
000045 'remit'
000046 'redro tros sserddA egnahC'
000047 'snocI egraL~'
000048 'ezis noci egraL stceleS'
000049 'snocI llamS~'
000050 'weiV nocI~'
000051 'sedoc noitacilppa fo weiv noci tceleS'
000052 'weiV liateD~'
000053 'sedoc noitacilppa fo weiv sliated tceleS'
000054 'weN~'
000055 'tidEppA'
000056 ')s(metI tidE'
000057 '}retnE{'
000058 'metI ddA'
000059 ')s(metI eteleD'
000060 'draobpilC ot drowssaP ypoC'
000061 'epacsteN ni LRU nepO'
000062 '>tluafed<'
000063 'sdrowssap PSI dna liamE ,beW'
000064 'sdrowssaP tenretnI'
000065 'eliF~ nocI nepO'
000066 'remiT'
000067 'srebmun NIP drac tiderc dna knaB'
000068 'srebmuN NIP'
000069 'nocI lanretnI~ tceleS'
000070 'snoitanibmoc efaS/kcoL'
000071 'snoitanibmoc kcoL'
000072 'ezis noci llamS stceleS'
000073 'sterces denifed resU'
000074 'sedoC resU'
000075 'drocer wen a etaerc ot kcilC'
000076 'sdrowssap rehtO'
000077 '2 sedoC resU'
000078 ':wodniw daol tonnaC'
000079 '!rorrE'
000080 'kO'
000081 'noiteled rof detceles smeti oN'
000082 'ofnI'
000083 'seY'
000084 'oN'
000085 '?meti siht eteled ot tnaw uoy erus uoy erA'
000086 'gninraW'
000087 ' eseht eteled ot tnaw uoy erus uoy erA'
000088 '?smeti '
000089 '!ereh sLRU on era erehT'
000090 '!meti siht htiw detaicossa LRU on si erehT'
000091 '!resworb deificeps on si erehT'
000092 '!hcnual ot deliaf epacsteN'
000093 'rorrE'
000094 '!trohs oot si drowssaP'
000095 'eybeyB'
000096 '!deripxE tcudorP'
000097 '!rrrrrorrE'
000098 'drowssaP dilavnI'
000099 'nocI'
000100 'noitpircseD'
000101 'resU'
000102 'drowssaP'
000103 'N/S'
000104 'etadpU tsaL'
000105 'etaD pxE'
000106 'LRU'
000107 'etoN'
000108 'drowssap knalb ro lecnac resU'
000109 'nwod gnittuhS'
000110 '.smeti erom ro eno tceles tsrif tsum uoY'
000111 'noitamrofnI'
000112 'esabatad detpyrcne*nu* 2/gniRyeK evaS'
000113 'detceles smeti oN'
000114 'detceles meti eno naht eroM'
000115 ' htiw snoitacinummoC'
000116 '!deliaf '
000117 'nmuloC drowssaP ediH'
000118 'nmuloC drowssaP wohS'
000119 'detceles si meti eno naht eroM'
000120 '!gninraW'
000121 'detceles saw meti oN'
000122 'noitartsigeR/tuobA 2/gniRyeK'
000123 'noitartsigeR/tuobA'
000124 'kO~'
000125 'tixe ot kcilC'
000126 '.pleh rof 1F sserP  .eman tsrif ruoy retnE'
000127 'ereh eman tsal ruoy retnE'
000128 'emaN tsaL'
000129 'emaN tsriF'
000130 '# geR'
000131 'ereh rebmun noitartsigeR retnE'
000132 '# laireS'
000133 'ereh rebmun laireS retnE'
000134 ''
000135 ''
000136 'terceS tidE'
000137 'noitamrofnI terceS tidE'
000138 'evaS'
000139 'margorp niam ot nruter dna stide ruoy evaS'
000140 'tiuQ'
000141 'segnahc ruoy trobA'
000142 'ofni terces siht fo noitpircseD'
000143 ':noitpircseD'
000144 'ctE ,eman nigol ,saila ,eman ruoY'
000145 ':DI resU'
000146 'terces siht rof ctE ,rebmun NIP ,noitanibmoc ,rebmun laireS'
000147 ':rebmuN laireS'
000148 '.ctE ,nigol ,egap bew ,noitacilppa siht rof drowssaP'
000149 ':drowssaP'
000150 ':LRU'
000151 'terces siht rof LRU'
000152 'terces siht rof etoN'
000153 ':etoN'
000154 ')ylno gninraw( noitaripxe drowssap ot syaD'
000155 ':gninraW eripxE drowssaP ot syaD'
000156 '!ogol a m'I'
000157 'snoitpo rof kcilc thgir ro ,ereh noci na porD'
000158 'uneMceRtidE'
000159 'drowssaP tsegguS'
000160 'esaC rewoL'
000161 'esaC reppU'
000162 'esaC dexiM'
000163 'ahplA'
000164 'ciremuN'
000165 'ciremuN-ahplA'
000166 'noitautcnuP + ciremunahplA'
000167 'uneMnocI'
000168 'eliF nocI nepO'
000169 'nocI lanretnI tceleS'
000170 'terces siht rof nocI na tceleS'
000171 '171000mk'
000172 'seY~'
000173 'oN~'
000174 '?drowssap gnitsixe eht etirwrevo ot tnaw uoy erus uoy erA'
000175 'gnikroW 2/gniRyeK'
000176 '...gnitpyrceD/gnitpyrcnE'
000177 '1'
000178 '...gnikroW'
000179 'puteS 2/gniRyeK'
000180 'sretemarap enil dnammoc dna emanelif/htap resworb retnE'
000181 'noitacoL epacsteN'
000182 'hcraeS'
000183 'golaid elif pu pop ot ereh kcilC'
000184 'cseD'
000185 'ffo/no nmuloc noitpircseD nruT'
000186 'ffo/no nmuloc nocI nruT'
000187 'ffo/no nmuloc drowssaP nruT'
000188 'DI resU'
000189 'ffo/no nmuloc )eman( DI resU nruT'
000190 'ffo/no nmuloc rebmuN laireS nruT'
000191 'dpU tsaL'
000192 'ffo/no nmuloc etadpU tsaL nruT'
000193 'etad pxE'
000194 'ffo/no nmuloc etaD noitaripxE drowssap nruT'
000195 'ffo/no nmuloc LRU nruT'
000196 'ffo/no nmuloc etoN nruT'
000197 'sppA'
000198 'WWW'
000199 'NIP'
000200 'snoitanibmoC'
000201 '1 - rehtO'
000202 '2 - rehtO'
000203 'tixE'
000204 'tiuq dna segnahc evaS'
000205 'neercS gaN tcudorP deretsigernU'
000206 '!pots ti ekaM  !pots ti ekaM'
000207 '!yawa og lliw neercs siht dna ,retsigeR  :nac uoY'
000208 '5'
000209 '?retsigeR I od woH~'
000210 'rotceleS nocI rgMetiS'
000211 'rotceleS nocI 2/gniRyeK'
000212 'snocI'
000213 '.noci sti tes ot dleif nocI rotidE eht ot snoci eseht fo eno garD'
000214 'esolC'
000215 'nigoL 2/gniryeK'
000216 'ni gol esaelP - 2/gniRyeK'
000217 'drowssaP retsaM eht gnisu eliF esabataD tnerruC nepO'
000218 'lecnaC'
000219 '2/gniRyeK trobA'
000220 'ereh seog egassem epyt noitpyrcnE'
000221 '2/SO rof repeeK drowssaP eruceS'
000222 ''
000223 ':drowssaP retsaM'
000224 'evitisnes esac - esarhp ro drowssap retsam ruoy retnE'
000225 ':tniH'
000226 ')erucsbo ti ekam( drowssap retsam ruoy fo uoy dnimer ot tniH'
000227 'unem rof kcilc thgiR - emanelif esabataD tnerruC'
000228 ':eliF esabataD tnerruC'
000229 'elif esabatad 2/gniRyeK a tceleS'
000230 '.unem rof kcilc thgiR - emanelif esabataD tnerruC'
000231 'sA evaS - 2/gniRyeK'
000232 ':emaN eliF sA-evaS'
000233 '.unem rof kcilc thgiR  ;eman wen a tceleS'
000234 'eman elif esabatad drowssap wen a retne esaelP'
000235 'csD'
000236 'dpU'
000237 'rsU'
000238 'N/S'
000239 'wP'
000240 'nocI'
000241 'tenretnI'
000242 'snoitacilppA'
000243 'sNIP'
000244 'sobmoC kcoL'
000245 '1 resU'
000246 '2 resU'
000247 'ssoB'
000248 'tropmI~'
000249 'egnahC egaugnaL~'
000250 'ettelaP tnoF~'
000251 'ymmud'
000252 'egaugnal neercs wen a tceleS'
000253 'tnof a esoohC'
000254 'elif tropmi txet raelc a tceles esaelP'
000255 'etirwrevO'
000256 'niagA yrT'
000257 '!nettirwrevo eb lliw ti - stsixe '
000258 'gninraW etirwrevO eliF'
000259 ''
000260 '!drowssap dilavnI'
000261 '!emaneliF esabataD dilavnI'
000262 '.tsixe ton seod '
000263 '.elif esabatad wen gnitaerC'
000264 'stnoF motsuC'
000265 ')putrats rewols( stnof deppord/gard no snruT'
000266 'drowssap weN'
000267 'rotidE drowssaP 2/gniryeK'
000268 'drowssap retsam wen eht evaS'
000269 'tixE~'
000270 'drowssap retsam wen eht gnivas tuohtiw tiuQ'
000271 'elif tnerruc eht rof drowssap wen a retnE'
000272 '*yltcaxe* drowssap retsam wen eht epyter esaelP'
000273 ':drowssaP retsaM weN'
000274 ':drowssaP retsaM yfireV'
000275 'yrteR'
000276 'eruliaF noitacifireV drowssaP'
000277 'EXE resworB'
000278 'sdrowssap tenretnI fo tsiL'
000279 'sedoc noitartsiger dna sdrowssap noitacilppa fo tsiL'
000280 'srebmun DI lanosrep drac tiderc dna knab fo tsiL'
000281 'snoitanibmoc kcol dna efas fo tsiL'
000282 'sterces deificeps resu fo tsiL'
000283 'sterces deificeps resu fo tsiL'
000284 ':etaD noitaripxE tnerruC'
000285 '.moor eht ni sklaw enoemos nehw sterces ruoy edih ylkciuq ot egap siht esU'
000286 'weN'
000287 '!dnuof sdrocer deripxe oN'
000288 'sdroceR deripxE'
000289 'sdroceR deripxE 2/gniRyeK'
000290 'sdrowssaP deripxE'
000291 'setad noitaripxe rieht tide ot sdrocer no kcilc elbuoD'
000292 ''
000293 'yad noitaripxe drowssaP'
000294 'htnom noitaripxe drowssaP'
000295 ')ylno gninraw( noitaripxe drowssap ot syaD'
000296 'etad noitaripxe drowssap etadpU'
000297 'etaD noitaripxE tnerruC'
000298 '6 gP koobetoN'
000299 'scihparg dnuorgkcab egap egnahc ot ereh elif PMB 2/SO na porD .meht tide ot seman nmuloc kcilc elbuoD'
000300 'tfel ot eman nmuloc evom ot kcilC'
000301 'eman nmuloc siht wohS/ediH'
000302 'thgir ot eman nmuloc detceles evom ot kcilC'
000303 '5 gP koobetoN'
000304 '4 gP koobetoN'
000305 '3 gP koobetoN'
000306 '1 gP koobetoN'
000307 'tfel ot eman nmuloc detceles evom ot kcilC'
000308 'peek ot selif XWP pukcab fo rebmuN'
000309 'snoitareneG pukcaB'
000310 'stluafed esU~'
000311 'stluafed ot seman egap dna dleif teseR'
000312 'tnih egap egnahc ot kcilc thgiR ;eman egap eht retnE'
000313 '2 gP koobetoN'
000314 ' drowssaP'
000315 ' nocI'
000316 ' etaD noitaripxE'
000317 ' etadpU tsaL'
000318 ' LRU'
000319 'eman nmuloc eht tidE'
000320 'emaN nmuloC'
000321 ' rof tniH'
000322 'tniH'
000323 'tnih nmuloc eht tidE'
000324 ' egap rof tnih retnE'
000325 'dnuoS aidemitluM elbasiD/elbanE'
000326 'golaid elif rof kcilc thgir - putrats ta yalp ot elif dnuos a retnE'
000327 'tluafed ot treveR~'
000328 '!gnitrever rof detceles meti oN'
000329 '!deripxE esabataD'
000330 'retsigeR~'
000331 'nottub siht kcilc dna edoc noitartsiger ruoy retnE'
000332 ''
000333 '333000MK'
000334 'eman ruoY'
000335 ')deilppus fi( sserdda ruoY'
000336 'etats dna ytic ruoY'
000337 'yrtnuoc dna edoC latsoP/piZ ruoY'
000338 'sserdda liame ruoY'
000339 'edoc noitartsiger retcarahc 61 ruoY'
000340 ':emaN'
000341 ':rddA'
000342 ':etatS/ytiC'
000343 ':yrtnuoC/piZ'
000344 ':liamE'
000345 ':edoC geR'
000346 'yna fi ,stimil lanoitarepO'
000347 ':stimiL'
000348 'resU deretsigeR'
000349 ':ynapmoC'
000350 'eman ynapmoc ruoY'
000351 'edoM omeD'
000352 'noitaripxe drowssap ot syaD'
000353 'etad noitaripxe drowssap etadpU'
000354 ''
000355 'pleH'
000356 ')GER.EMDAER ees( edoc noitartsiger ruoy retne esaelP'
000357 'edoCgeR'
000358 'edoC noitartsigeR dilavni ro gnissiM !rorrE'
000359 '!woN~ retsigeR'
000360 'dnuoS'
000361 'sdnuoS aidemitluM elbanE'
000362 ':elif siht yalP'
000363 'uneMemaNdlF'
000364 'putrats ta yalp ot elif aidemitlum a tceleS'
000365 'txeT'
000366 ' ni eripxe lliw elif esabatad sihT'
000367 '!syad '
000368 'selif CWP rof erutaef tropmI eht esu esaelP'
000369 '963000MK'
000370 '073000MK'
000371 ')ylno gninraw( noitairpxe drowssap ot syaD'
000372 'etad noitairpxe drowssap etadpU'
000373 '373000MK'
000374 '.esabatad dna drowssap dlo gnisU ;detroba sA evaS'
000375 '!esabatad siht rof drowssap retsam eht degnahc evah uoY'
000376 '.deretne tsuj uoy eno eht ot drowssap retsam eht egnahc ot drowssaP weN esU tceleS'
000377 'drowssap dlo eht esuer ot drowssaP dlO esU tceleS'
000378 'drowssaP weN~ esU'
000379 'drowssaP dlO~ esU'
000380 '!eludom noitpyrcne eht gnissim era uoY'
000381 '.tcudorp lluf eht yb elbasu eb ton lliw dna tamrof elbadaer a ni derots eb lliw sterces ruoy ,deecorp uoy fI'
000382 '.eludom noitpyrcne na gniniatbo no sliated rof moc.cni-kdi@2rk liamE'
000383 'deecorp dna gninraw erongI'
000384 '!gninraW !gninraW !gninraW'
000385 ' rof notaiverbba redils tros eht tidE'
000386 '!sretcarahc 4 si htgnel noitaiverbba tros mumixaM'
000387 '783000MK'
000388 '.esabatad wen ruoy sa elif txet detpyrcnenu na tropmI'
000389 '2/gniRyeK fo sgnittes egnahC'
000390 'draobpilC ot emanresU ypoC'
000391 'egap rehtona ot )s(metI evoM'
000392 'raey noitaripxe drowssaP'
000393 'egap rehtona ot )s(metI ypoC'
000394 'troS'
000395 '593000MK'
000396 '693000MK'
000397 '793000MK'
000398 '893000MK'
000399 '993000MK'
000400 '004000MK'
000401 '104000MK'
000402 '204000MK'
000403 '304000MK'
000404 '404000MK'
000405 '504000MK'
