{ Filename:~modname~    Version:~version~     Date:~MNAme~ ~day~, ~fullyear~  ~time~
*
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer     Description
* ~log~
*
*
* ~nokeywords~
*
* Description
* -----------
* Purpose:
*
*
*
****************************************************************************

}

    {$DEFINE USECBC}
    {.$DEFINE AllowIsamErrorMessages}
    {$DEFINE AllowOPROErrorMessages}
    {.$DEFINE AllowAproErrorMessages}
    {.$DEFINE AllowFilerErrorMessages}

    {************************************************************************}
    {************************************************************************}
