{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Security constants
*
* ~notesend~
* ~nokeywords~
*
****************************************************************************

}

UNIT SECONST;

INTERFACE

    {E/}

CONST
    SECON1N        = 35621;
    SECON1P        = 207;
    SECON1S        = 'BF';

    {-------------------------------}

    {I/}

CONST
    SECON2N        = 52066;
    SECON2P        = 150;
    SECON2S        = '4';

    {-------------------------------}

    {?/}

CONST
    SECON3N        = 35437;
    SECON3P        = 23;
    SECON3S        = '*≈';

    {-------------------------------}

    {R/}

CONST
    SECON4N        = 55827;
    SECON4P        = 190;
    SECON4S        = '4';

    {-------------------------------}

    {W/}

CONST
    SECON5N        = 5939;
    SECON5P        = 151;
    SECON5S        = 'ù÷';

    {-------------------------------}

    {ruHxpxrxdmabiVrl}

CONST
    SECON6N        = 62496;
    SECON6P        = 56;
    SECON6S        = 'T∞6p7¢æ@Çß9Qü=/Z';

    {-------------------------------}

    {yPpbpcpqapxysjhr}

CONST
    SECON7N        = 9308;
    SECON7P        = 248;
    SECON7S        = 'î=_w%—e|&òsjÜ∂’';

    {-------------------------------}

    {/}

CONST
    SECON8N        = 31146;
    SECON8P        = 77;
    SECON8S        = '9';

    {-------------------------------}

    {NewsMaker Systems }

CONST
    SECON9N        = 15219;
    SECON9P        = 226;
    SECON9S        = '=G1$8o'#13'd'#10#255'bõGLK|';

    {-------------------------------}

    {Problem reading dongle}

CONST
    SECON10N       = 35692;
    SECON10P       = 216;
    SECON10S       = 'ã$bsn—±<…˘]ßT=‘v”⁄R';

    {-------------------------------}

    {Dongle Security Compromised!}

CONST
    SECON11N       = 7017;
    SECON11P       = 29;
    SECON11S       = 'hΩΩ_î\ò+åSh]ÃmÌ≥‰q∂«%Ày'#41'R';

    {-------------------------------}

    {Invalid Dongle Header}

CONST
    SECON12N       = 57893;
    SECON12P       = 1;
    SECON12S       = 'ÂgD'#9'L˙Cu¢º÷Bπbú¶¥’_∫';

    {-------------------------------}

    {SN: }

CONST
    SECON13N       = 60389;
    SECON13P       = 111;
    SECON13S       = '<¿'#255'µ';

    {-------------------------------}

    {Problem writing dongle}

CONST
    SECON14N       = 38019;
    SECON14P       = 94;
    SECON14S       = '§KÜfxÇƒÏvjæ=Ã!ÿ'#0'Ìaw';

    {-------------------------------}

    {Checking for viruses.  Please Wait...}

CONST
    SECON15N       = 64428;
    SECON15P       = 235;
    SECON15S       = 'jìûYwP–pøå5≤%'#0#13'fŒ·'#0'À¬ì˙'#255'PîÄÓÎÛ';

    {-------------------------------}

    {Virus Check Complete.}

CONST
    SECON16N       = 48292;
    SECON16P       = 185;
    SECON16S       = 'â±Óﬂ.∆'#123'ãü?W©o%ÇWò–';

    {-------------------------------}

    {hh:mm:ss}

CONST
    SECON17N       = 13876;
    SECON17P       = 246;
    SECON17S       = 'Û:•É?æ¡';

    {-------------------------------}

    {NEN-ENIGMA}

CONST
    SECON18N       = 50933;
    SECON18P       = 214;
    SECON18S       = '›'#26'∫,b™ª4e#';

    {-------------------------------}

    {Invalid parameter string}

CONST
    SECON19N       = 6316;
    SECON19P       = 163;
    SECON19S       = '€˙,∫dêö“2°˛˛ö†⁄˚~'#39'cw';

    {-------------------------------}

    {Missing Dongle}

CONST
    SECON20N       = 40311;
    SECON20P       = 29;
    SECON20S       = '£øﬁÓ, o>gÒæy ';

    {-------------------------------}

    {Invalid request char}

CONST
    SECON21N       = 57610;
    SECON21P       = 151;
    SECON21S       = '¬jw≤àq-ÊŸÙ√'#9' à»HËr';

    {-------------------------------}

    {Invalid BIOS address}

CONST
    SECON22N       = 9635;
    SECON22P       = 84;
    SECON22S       = 'Eÿ§ÿ'#41'„ê≤.#ì√∑ì∂ZÅJW˚';

    {-------------------------------}

    {driver corrupted}

CONST
    SECON23N       = 1422;
    SECON23P       = 47;
    SECON23S       = '’å¬`ú9$·¿5Ix—';

    {-------------------------------}

    {busy or missing}

CONST
    SECON24N       = 51010;
    SECON24P       = 178;
    SECON24S       = '`¨Øâ7ÿ–K√Â#6ãø@';

    {-------------------------------}

    {OS/2 parallel port access failure}

CONST
    SECON25N       = 8766;
    SECON25P       = 236;
    SECON25S       = '∞Yx\'#4'zxEbµÉ„øØèõko"mBm’Ùyo˜ãQV';

    {-------------------------------}

    {Windows task ID not found in handle table}

CONST
    SECON26N       = 30473;
    SECON26P       = 209;
    SECON26S       = 'ª<ﬁctô'#10'∂2Ì!‰'#9'=ÌBj=CÄn'#10'r'#40'˛'#9#26'LÊÔgŸW';

    {-------------------------------}

    {Sentinel Error: }

CONST
    SECON27N       = 59895;
    SECON27P       = 64;
    SECON27S       = 'l"‹Mﬁ.éÅ Ú\d>•p';

    {-------------------------------}

    {Dongle nearing end of R/W lifetime!}

CONST
    SECON28N       = 10707;
    SECON28P       = 231;
    SECON28S       = 'X¬,’'#10'¸®÷P'#13'˛«-◊1'#4'O≥ªyŒúg–8Y^x⁄Áö';

    {-------------------------------}

    {cIMa GAlINa}

CONST
    SECON29N       = 8268;
    SECON29P       = 131;
    SECON29S       = 'íph'#39']öÿıÊ≈'#123;

    {-------------------------------}

    {Access Failure}

CONST
    SECON30N       = 51629;
    SECON30P       = 87;
    SECON30S       = 'œ‚˛S≠Ü∫?‚;Ô';

    {-------------------------------}

    {Demo Mode - Feature set reduced}

CONST
    SECON31N       = 11587;
    SECON31P       = 42;
    SECON31S       = 'ˆ'#41'uynÖ¡…`9≤0Æ>/'#26'!'#40'ñ|¸ﬁíËtÁ>ö,ï';

    {-------------------------------}

    {Full Name :}

CONST
    SECON32N       = 54555;
    SECON32P       = 118;
    SECON32S       = '›õ0á~˚ ≈ö†'#0;

    {-------------------------------}

    {Challenge :}

CONST
    SECON33N       = 63860;
    SECON33P       = 253;
    SECON33S       = 'U<º≥œÈaëYÏÂ';

    {-------------------------------}

    {Reply     :}

CONST
    SECON34N       = 31283;
    SECON34P       = 174;
    SECON34S       = '[G€eb´'#255'r&Ì';

    {-------------------------------}

    {Refresh Key}

CONST
    SECON35N       = 58948;
    SECON35P       = 28;
    SECON35S       = 'Ü-˛≥\Îe;¨';

    {-------------------------------}

    {KKKKKKKK}

CONST
    SECON36N       = 54847;
    SECON36P       = 59;
    SECON36S       = 'h´ìXÊ¬'#125'"';

    {-------------------------------}

    {Enter your name}

CONST
    SECON37N       = 40465;
    SECON37P       = 36;
    SECON37S       = '®⁄®ƒT'#0'⁄Û~'#4'Œ‚.Œ';

    {-------------------------------}

    {Call customer support!}

CONST
    SECON38N       = 21443;
    SECON38P       = 248;
    SECON38S       = '[√ñéç$£ﬁ3¿»ıÙ¿Vé$';

    {-------------------------------}

    {Enter user challenge}

CONST
    SECON39N       = 12010;
    SECON39P       = 81;
    SECON39S       = ' få»-Â$∂/âG~^’∑X0';

    {-------------------------------}

    {Recharge Successful}

CONST
    SECON40N       = 21295;
    SECON40P       = 29;
    SECON40S       = 's©¥l7>BÚzh7'#255'4”îpú!'#4;

    {-------------------------------}

    {Recharge Failure}

CONST
    SECON41N       = 21619;
    SECON41P       = 36;
    SECON41S       = '‡4Æ>£'#32'¯ìØ‰ƒîƒ˛';

    {-------------------------------}

    {Demo Mode}

CONST
    SECON42N       = 5122;
    SECON42P       = 231;
    SECON42S       = #26'∫ÛS`:èì';

    {-------------------------------}

    {NEN.KEY}

CONST
    SECON43N       = 59697;
    SECON43P       = 48;
    SECON43S       = '7µ-P'#10'¶r';

    {-------------------------------}

    {C:\~~~.~~~}

CONST
    SECON44N       = 20042;
    SECON44P       = 247;
    SECON44S       = ']Úq|'#39'S€H';

    {-------------------------------}

    {Key Refresh Required}

CONST
    SECON45N       = 174;
    SECON45P       = 55;
    SECON45S       = #9'6g√UÉ¯‰34|πÙüaX˙';

    {-------------------------------}

    {Key Expires Soon.  Call NewsMaker!}

CONST
    SECON46N       = 58158;
    SECON46P       = 47;
    SECON46S       = 'ô©‚†]Œ_Lä!ù3ûhp,êA[“æ™®d'#0'ﬂQåBr'#39'ùí';

    {-------------------------------}

    {>:TAGS}

CONST
    SECON47N       = 30465;
    SECON47P       = 240;
    SECON47S       = '2+Ø';

    {-------------------------------}

    {Tell the user the new Hex reply and have him type it in}

CONST
    SECON48N       = 19783;
    SECON48P       = 171;
    SECON48S       = '6í¢z„ﬂ±î§G6f^œ'#40'⁄˝∆Òè•c√Z¬‘Aª⁄'#125'“ÖŒ'#26'n˝ˇAÓüeÏáÂ®√F';

    {-------------------------------}

    {Enter the users EXACT name}

CONST
    SECON49N       = 45955;
    SECON49P       = 222;
    SECON49S       = 'ã¬Q°¡Å¶EäÙ˛>¨rT¶tB¥`#3¨Ú';

    {-------------------------------}

    {Enter users challenge password}

CONST
    SECON50N       = 34833;
    SECON50P       = 35;
    SECON50S       = 'hí"‰|‘È˘â'#40'ÒW‰#ºÕä—V'#39'íìç'#41'r';

    {-------------------------------}
    {nenrply}

CONST
    SECON51N       = 63103;
    SECON51P       = 150;
    SECON51S       = '“imaXW';


IMPLEMENTATION
END.
    {-------------------------------}
    {-------------------------------}
