{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "You are not authorized to run this product version.  Use an older one."
*
* Created by CryptCon v~version~ on 07-26-1995 14:36:27
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {You are not authorized to run this product version.  Use an older one.}

CONST
    SESTR9N        = 6822;
    SESTR9P        = 115;
    SESTR9S        = '8ÃC¿Óü˙Í§ä·Òz8D»Îÿ”ë‚PÑ'#10'ú&î˜'#13'å–∆≠è |™9/Lõ[Ìnìﬁ'#125'ÎQˆÿö∏_'#40'rö_';

