{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Key recharge failed"
*
* Created by CryptCon v~version~ on 07-26-1995 14:35:47
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {Key recharge failed}

CONST
    SESTR7N        = 58330;
    SESTR7P        = 197;
    SESTR7S        = 'í8ÏÃ×ô3ææ®«'#41' ñ'#40'5Ö';

