{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Key charge expired"
*
* Created by CryptCon v~version~ on 07-26-1995 14:35:25
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {Key charge expired}

CONST
    SESTR5N        = 49256;
    SESTR5P        = 65;
    SESTR5S        = 'ØZÄg7bàD#êﬁLÕ@ôç';

