{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Semaphore failure"
*
* Created by CryptCon v~version~ on 07-26-1995 14:35:35
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {Semaphore failure}

CONST
    SESTR6N        = 46284;
    SESTR6P        = 46;
    SESTR6S        = '#'#26'õbYÃÿm–'#26'∂@„®5';

