{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "The Design Group"
*
* Created by CryptCon v~version~ on 09-11-1995 08:20:06
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


{The Design Group}

CONST
    SESTR14N = 21315;
    SESTR14P = 234;
    SESTR14S = 'bèKêÍŒ<ÕÃðÁ'#41'‰9';

