{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Product not authorized on this server or dongle"
*
* Created by CryptCon v~version~ on 07-26-1995 14:36:00
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {Product not authorized on this server or dongle}

CONST
    SESTR8N        = 53023;
    SESTR8P        = 207;
    SESTR8S        = 'E6Oqö-€–'#13'Ô5«JBx£œWé9ð\ÈŒ…ÒBcPAë'#123'Ÿz^Þ‹dö·ÙÜ|£*Ø';

