{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Access failure.  Contact support!"
*
* Created by CryptCon v~version~ on 09-10-1995 18:28:07
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


{Access failure.  Contact support!}

CONST
    SESTR13N = 19784;
    SESTR13P = 146;
    SESTR13S = 'ÀM8/Dø'#123'z—­ƒ±ô¶'#125'†Ž¥Jü5°eCÄPbh';

