{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Stop working on this date"
*
* Created by CryptCon v~version~ on 09-10-1995 15:32:32
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


{Stop working on this date}

CONST
    SESTR11N = 6163;
    SESTR11P = 133;
    SESTR11S = '²¶S@©´é_ƒ ÞóQ'#123'HèÕhá'#41'ÄzMu';

