{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "Max workstation license count exceeded!"
*
* Created by CryptCon v~version~ on 07-26-1995 14:35:02
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {Max workstation license count exceeded!}

CONST
    SESTR3N        = 54927;
    SESTR3P        = 253;
    SESTR3S        = '*§²öä¾ä–õ!ïË¦ö&Û:l*B¼Å©¯Ü_òå€[•‰•';

