{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "RTC failure"
*
* Created by CryptCon v~version~ on 07-26-1995 14:35:10
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {RTC failure}

CONST
    SESTR4N        = 39533;
    SESTR4P        = 246;
    SESTR4S        = '.ò ón_W÷';

