{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "IDK, Inc."
*
* Created by CryptCon v~version~ on 09-11-1995 08:20:12
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


{IDK, Inc.}

CONST
    SESTR15N = 27760;
    SESTR15P = 234;
    SESTR15S = '¸mÐÊg‡x';

