{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
* Crypted String 
*
* "This product has expired!"
*
* Created by CryptCon v~version~ on 07-26-1995 14:36:38
*
* CryptCon created by Kevin G. McCoy
*
* ~notesend~
* ~nokeywords~
*
***************************************************************************
}


    {This product has expired!}

CONST
    SESTR10N       = 65210;
    SESTR10P       = 84;
    SESTR10S       = 'Hä0‹‘‘aTŸ'#40'jz©Å$…ãè;?ø';

