;-------------------------------;
; Copyright (C) 1999 IDK, Inc.  ;
;     http://www.idk-inc.com    ;
;   Virtual Language Msg File   ;
;   ~nokeywords~                ;
;-------------------------------;
; Languages supported:          ;
; 1 - English                   ;
; 2 - Polski  (Polish)          ;
; end of list                   ;
;-------------------------------;
000001 'Are you sure you want to lose all your changes (if any)?'
000001 'Czy chcesz stracic wszystkie zmiany?'
000002 'KeyRing/2'
000002 'KeyRing/2'
000003 'Save database changes'
000003 'Zapisz zmiany bazy danych'
000004 'Get help on KeyRing/2'
000004 'Pomoc o KeyRing/2'
000005 'Close KeyRing/2'
000005 'Zakoncz KeyRing/2'
000006 'Hide password column'
000006 'Ukryj kolumne hasel'
000007 'Open browser on current URL entry'
000007 'Wystartuj przegladarke za biezacym adresem URL'
000008 'Change KeyRing/2 Settings'
000008 'Zmien ustawienia KeyRing/2'
000009 'Open/Create password database'
000009 'Otworz/zbuduj baze danych hasel'
000010 '45'
000010 '45'
000011 'No conversation active.'
000011 'Brak aktywnej konwersacji'
000012 '~File'
000012 '~Plik'
000013 '~Open'
000013 '~Otworz'
000014 'Open a new password database'
000014 'Otworz nowa baze danych hasel'
000015 '~Save'
000015 '~Zapisz'
000016 'Save the current database'
000016 'Zapisz biezaca baze danych'
000017 'Save ~As'
000017 'Z~apisz Jako'
000018 'Save the current database under a new name'
000018 'Zapisz biezaca baze danych pod nowa nazwa'
000019 'Se~tup'
000019 'Us~tawienia'
000020 'Save the database as an unencrypted text file'
000020 'Zapisz baze danych jako zakodowany zbior tekstowy'
000021 '~Export'
000021 '~Eksport'
000022 '~Print'
000022 '~Drukuj'
000023 'print all database entries and passwords'
000023 'drukuj wszystkie dokumenty bazy danych i hasla'
000024 '-'
000024 '-'
000025 'E~xit'
000025 '~Koniec'
000026 'Quit KeyRing/2'
000026 'Zakoncz KeyRing/2'
000027 '~Help'
000027 '~Pomoc'
000028 'Help ~Index'
000028 '~Index pomocy'
000029 'View table of contents on KeyRing/2 topics'
000029 'Spis tresci na temat KeyRing/2'
000030 '~General Help'
000030 'Pomoc ~Ogolna'
000031 'View help on general OS/2 application topics'
000031 'Ogolna pomoc o aplikacjach w OS/2'
000032 '~Using Help'
000032 '~Uzywanie Pomocy'
000033 'View information on how to use the help system'
000033 'Informacja jak uzywac systemu pomocy'
000034 '~Keys help'
000034 'Pomoc o ~Klawiszach'
000035 'View help on hotkeys and mouse actions'
000035 'Pomoc o uzyciu myszy i klawiszy skrotowych'
000036 'Key~ring2 Help'
000036 'Pomoc Key~ring2'
000037 'View KeyRing/2 general help'
000037 'Ogolna pomoc o KeyRing/2'
000038 '~Product Information'
000038 'Informacja o ~Produkcie'
000039 'View product version and registration'
000039 'Pokaz versje produktu i rejestracje'
000040 'TimerMenu'
000040 'MenuStopera'
000041 'Kill Timer'
000041 'Likwiduj Stoper'
000042 'Application passwords and registration codes'
000042 'Hasla aplikacji i kody rejestracyjne'
000043 'Application Codes'
000043 'Kody aplikacji'
000044 'Check database for expired passwords'
000044 'Wyszukaj przeterminowane hasla w bazie danych'
000045 'timer'
000045 'stoper'
000046 'Change Address sort order'
000046 'Zmien kolejnosc sortowania adresow'
000047 '~Large Icons'
000047 '~Duze Ikony'
000048 'Selects Large icon size'
000048 'Zmien na duze ikony'
000049 '~Small Icons'
000049 '~Male Ikony'
000050 '~Icon View'
000050 'Pokaz ~Ikony'
000051 'Select icon view of application codes'
000051 'Pokaz kody aplikacji ikonograficznie'
000052 '~Detail View'
000052 'Pokaz ~Szczegoly'
000053 'Select details view of application codes'
000053 'Pokaz kody aplikacji szczegolowo'
000054 '~New'
000054 '~Nowy'
000055 'AppEdit'
000055 'AppEdit'
000056 'Edit Item(s)'
000056 'Edycja elementu(ow)'
000057 '{Enter}'
000057 '{Enter}'
000058 'Add Item'
000058 'Dodaj Element'
000059 'Delete Item(s)'
000059 'Usun Element(y)'
000060 'Copy Password to clipboard'
000060 'Skopiuj haslo do schowka'
000061 'Open URL in Netscape'
000061 'Wystartuj przegladarke na URL'
000062 '<default>'
000062 '<domyslne>'
000063 'Web, Email and ISP passwords'
000063 'Hasla WWW, poczty i dostepu do Internetu (ISP)'
000064 'Internet Passwords'
000064 'Hasla do Internetu'
000065 'Open Icon ~File'
000065 'Otworz ~Plik Ikon'
000066 'Timer'
000066 'Stoper'
000067 'Bank and credit card PIN numbers'
000067 'Numery bankowe i osobiste numery identyfikacyjne (PIN) kart kredytowych'
000068 'PIN Numbers'
000068 'Numery (PIN)'
000069 'Select ~Internal Icon'
000069 'Wybierz Ikone ~Wewnetrzna'
000070 'Lock/Safe combinations'
000070 'Kombinacje sejfow i zamkow'
000071 'Lock combinations'
000071 'Kombinacje zamkow'
000072 'Selects Small icon size'
000072 'Zmien na male ikony'
000073 'User defined secrets'
000073 'Sekrety uzytkownika'
000074 'User Codes'
000074 'Kody uzytkownika'
000075 'Click to create a new record'
000075 'Utworz nowy rekord'
000076 'Other passwords'
000076 'Inne hasla'
000077 'User Codes 2'
000077 'Kody uzytkownika 2'
000078 'Cannot load window:'
000078 'Blad ladowania okna:'
000079 'Error!'
000079 'Blad!'
000080 'Ok'
000080 'Ok'
000081 'No items selected for deletion'
000081 'Nie wybrano elementow do usuwania'
000082 'Info'
000082 'Info'
000083 'Yes'
000083 'Tak'
000084 'No'
000084 'Nie'
000085 'Are you sure you want to delete this item?'
000085 'Czy usunac ten element'
000086 'Warning'
000086 'Ostrzezenie'
000087 'Are you sure you want to delete these '
000087 'Czy usunac te '
000088 ' items?'
000088 ' elementy?'
000089 'There are no URLs here!'
000089 'Nie ma tu URL!'
000090 'There is no URL associated with this item!'
000090 'Brak powiazania URL z tym elementem'
000091 'There is no specified browser!'
000091 'Brak definicji przegladarki'
000092 'Netscape failed to launch!'
000092 'Przegladarka nie wystartowala'
000093 'Error'
000093 'Blad'
000094 'Password is too short!'
000094 'Zbyt krotkie haslo!'
000095 'Byebye'
000095 'DoWidzenia'
000096 'Product Expired!'
000096 'Przeterminowany produkt!'
000097 'Errorrrrr!'
000097 'Blllaaadd!'
000098 'Invalid Password'
000098 'Nielegalne Haslo'
000099 'Icon'
000099 'Ikona'
000100 'Description'
000100 'Opis'
000101 'User'
000101 'Uzytkownik'
000102 'Password'
000102 'Haslo'
000103 'S/N'
000103 'N/S'
000104 'Last Update'
000104 'Ostatnia zmiana'
000105 'Exp Date'
000105 'Data Waznosci'
000106 'URL'
000106 'URL'
000107 'Note'
000107 'Notka'
000108 'User cancel or blank password'
000108 'Puste haslo lub polecenie konca pracy'
000109 'Shutting down'
000109 'Konczenie pracy'
000110 'You must first select one or more items.'
000110 'Wybierz conajmniej jeden element'
000111 'Information'
000111 'Informacja'
000112 'Save KeyRing/2 *un*encrypted database'
000112 'Zapisz *nie*zakodowana baze danych KR/2'
000113 'No items selected'
000113 'Nie wybrano elementow'
000114 'More than one item selected'
000114 'Wybrano wiecej niz jeden element'
000115 'Communications with '
000115 'Komunikacja z '
000116 ' failed!'
000116 ' zawiodla!'
000117 'Hide Password Column'
000117 'Chowaj kolumne hasel'
000118 'Show Password Column'
000118 'Pokaz kolumne hasel'
000119 'More than one item is selected'
000119 'Wybrano wiecej niz jeden element'
000120 'Warning!'
000120 'Ostrzezenie!'
000121 'No item was selected'
000121 'Nie wybrano elementu'
000122 'KeyRing/2 About/Registration'
000122 'O Produkcie/Rejestracja KeyRing/2'
000123 'About/Registration'
000123 'O Produkccie/Rejestracja'
000124 '~Ok'
000124 '~Ok'
000125 'Click to exit'
000125 'Kliknij aby skonczyc'
000126 'Enter your first name.  Press F1 for help.'
000126 'Podaj Imie. F1 wywola pomoc.'
000127 'Enter your last name here'
000127 'Podaj nazwisko'
000128 'Last Name'
000128 'Nazwisko'
000129 'First Name'
000129 'Imie'
000130 'Reg #'
000130 '# Rej'
000131 'Enter Registration number here'
000131 'Podaj rejestracyjny'
000132 'Serial #'
000132 '# seryjny'
000133 'Enter Serial number here'
000133 'Podaj numer seryjny'
000134 ''
000134 ''
000135 ''
000135 ''
000136 'Edit Secret'
000136 'Edycja sekretu'
000137 'Edit Secret Information'
000137 'Edycja zawartosci sekretu'
000138 'Save'
000138 'Zapisz'
000139 'Save your edits and return to main program'
000139 'Zapisz zmiany i wroc do programu glownego'
000140 'Quit'
000140 'Anuluj'
000141 'Abort your changes'
000141 'Anuluj zmiany'
000142 'Description of this secret info'
000142 'Opis tego sekretu'
000143 'Description:'
000143 'Opis:'
000144 'Your name, alias, login name, Etc'
000144 'Imie, pseudonim, identyfikator, itd'
000145 'User ID:'
000145 'ID uzytkownika:'
000146 'Serial number, combination, PIN number, Etc for this secret'
000146 'Numer seryjny, kombinacja, numer PIN, itd zwiazane z tym sekretem'
000147 'Serial Number:'
000147 'Numer seryjny:'
000148 'Password for this application, web page, login, Etc.'
000148 'Haslo dla applikacji, strony WWW, login, itp.'
000149 'Password:'
000149 'Haslo:'
000150 'URL:'
000150 'URL:'
000151 'URL for this secret'
000151 'URL tego sekretu'
000152 'Note for this secret'
000152 'Notka tego sekretu'
000153 'Note:'
000153 'Notka:'
000154 'Days to password expiration (warning only)'
000154 'Ilosc dni waznosci (dla ostrzezenia)'
000155 'Days to Password Expire Warning:'
000155 'Dni do ostrzezenia przeterminowania hasla:'
000156 'I'm a logo!'
000156 'To ja jestem logo!'
000157 'Drop an icon here, or right click for options'
000157 'Przenies tu ikone lub prawy klik'
000158 'EditRecMenu'
000158 'MenuEdycElem'
000159 'Suggest Password'
000159 'Zasugeruj haslo'
000160 'Lower Case'
000160 'Male litery'
000161 'Upper Case'
000161 'Duze litery'
000162 'Mixed Case'
000162 'Mieszane litery'
000163 'Alpha'
000163 'Litery'
000164 'Numeric'
000164 'Cyfry'
000165 'Alpha-Numeric'
000165 'Alfanumeryczne'
000166 'Alphanumeric + Punctuation'
000166 'Alfanumeryczne i punktuacyjne'
000167 'IconMenu'
000167 'MenuIkon'
000168 'Open Icon File'
000168 'Otworz zbior ikon'
000169 'Select Internal Icon'
000169 'Wybierz ikone wewnetrzna'
000170 'Select an Icon for this secret'
000170 'Wybierz ikone dla tego sekretu'
000171 'No Exp'
000171 'BezWaz'
000172 '~Yes'
000172 '~Tak'
000173 '~No'
000173 '~Nie'
000174 'Are you sure you want to overwrite the existing password?'
000174 'Czy chcesz wymienic istniejace haslo?'
000175 'KeyRing/2 Working'
000175 'KeyRing/2 Pracuje'
000176 'Encrypting/Decrypting...'
000176 'Szyfrowanie/Deszyfrowanie...'
000177 '1'
000177 '1'
000178 'Working...'
000178 'Pracuje...'
000179 'KeyRing/2 Setup'
000179 'Ustawienie KeyRing/2'
000180 'Enter browser path/filename and command line parameters'
000180 'Wprowadz pelny adres programu przegladarki i parametry startu'
000181 'Netscape Location'
000181 'Adres przegladarki'
000182 'Search'
000182 'Szukaj'
000183 'Click here to pop up file dialog'
000183 'Wywolaj dialog zbioru'
000184 'Desc'
000184 'Opis'
000185 'Turn Description column on/off'
000185 'Wlacz/wylacz kolumne opisu'
000186 'Turn Icon column on/off'
000186 'Wlacz/wylacz kolumne ikon'
000187 'Turn Password column on/off'
000187 'Wlacz/wylacz kolumne hasel'
000188 'User ID'
000188 'ID uzytkownika'
000189 'Turn User ID (name) column on/off'
000189 'Wlacz/wylacz kolumne ID uzytkownika'
000190 'Turn Serial Number column on/off'
000190 'Wlacz/wylacz kolumne numerow seryjnych'
000191 'Last Upd'
000191 'Ost Zm.'
000192 'Turn Last Update column on/off'
000192 'Wlacz/wylacz kolumne ostatniej zmiany'
000193 'Exp date'
000193 'Data Waz'
000194 'Turn password Expiration Date column on/off'
000194 'Wlacz/wylacz kolumne daty waznosci'
000195 'Turn URL column on/off'
000195 'Wlacz/wylacz kolumne URL'
000196 'Turn Note column on/off'
000196 'Wlacz/wylacz kolumne notek'
000197 'Apps'
000197 'Aplik'
000198 'WWW'
000198 'WWW'
000199 'PIN'
000199 'PIN'
000200 'Combinations'
000200 'Kombinacje'
000201 'Other - 1'
000201 'Inne - 1'
000202 'Other - 2'
000202 'Inne - 2'
000203 'Exit'
000203 'Koniec'
000204 'Save changes and quit'
000204 'Zapisz zmiany i zakoncz'
000205 'Unregistered Product Nag Screen'
000205 'Przypomnienie o zarejestrowaniu programu'
000206 'Make it stop!  Make it stop!'
000206 'Ach przestan!  Ach przestan!'
000207 'You can:  Register, and this screen will go away!'
000207 'Mozesz:   zarejestrowac i przypomnienie zniknie!'
000208 '5'
000208 '5'
000209 '~How do I Register?'
000209 '~Jak zarejestrowac?'
000210 'SiteMgr Icon Selector'
000210 'Wybor ikony SiteMgr'
000211 'KeyRing/2 Icon Selector'
000211 'Wybor ikon KeyRing/2'
000212 'Icons'
000212 'Ikony'
000213 'Drag one of these icons to the Editor Icon field to set its icon.'
000213 'Przenies jedna z ikon w pole Edytora celem przydzielenia'
000214 'Close'
000214 'Zamknij'
000215 'Keyring/2 Login'
000215 'Login Keyring/2'
000216 'KeyRing/2 - Please log in'
000216 'KeyRing/2 - Zaloguj sie, prosze'
000217 'Open Current Database File using the Master Password'
000217 'Otworz biezaca baze danych uzywajac glownego hasla'
000218 'Cancel'
000218 'Anuluj'
000219 'Abort KeyRing/2'
000219 'Przerwij KeyRing/2'
000220 'Encryption type message goes here'
000220 'Tu bedzie typ szyfrowania'
000221 'Secure Password Keeper for OS/2'
000221 'Bezpieczne przechowywanie hasel dla OS/2'
000222 ''
000222 ''
000223 'Master Password:'
000223 'Haslo Glowne:'
000224 'Enter your master password or phrase - case sensitive'
000224 'Podaj glowne haslo - male i duze litery rozrozniane'
000225 'Hint:'
000225 'Wskazowka:'
000226 'Hint to remind you of your master password (make it obscure)'
000226 'Wskazowka przypominajaca haslo glowne (niezbyt oczywista)'
000227 'Current Database filename - Right click for menu'
000227 'Biezaca baza danych - prawy klik wywola menu'
000228 'Current Database File:'
000228 'Zbior biezacej bazy danych:'
000229 'Select a KeyRing/2 database file'
000229 'Wybierz zbior bazy danych KeyRing/2'
000230 'Current Database filename - Right click for menu.'
000230 'Biezaca baza danych - prawy klik wywola menu.'
000231 'KeyRing/2 - Save As'
000231 'KeyRing/2 - Zapisz jako'
000232 'Save-As File Name:'
000232 'Zapisz jako zbior:'
000233 'Select a new name;  Right click for menu.'
000233 'Wybierz nowa nzawe; prawy klik wywola menu.'
000234 'Please enter a new password database file name'
000234 'Prosze podac a nowa nazwe zbioru bazy danych'
000235 'Dsc'
000235 'Opis"
000236 'Upd'
000236 'Z-na'
000237 'Usr'
000237 'Uzyt'
000238 'S/N'
000238 'N/S'
000239 'Pw'
000239 'Hasl'
000240 'Icon'
000240 'Ikna'
000241 'Internet'
000241 'Internet'
000242 'Applications'
000242 'Applikacje'
000243 'PINs'
000243 'PINy'
000244 'Lock Combos'
000244 'Kody zamkow'
000245 'User 1'
000245 'Uzytk1'
000246 'User 2'
000246 'Uzytk2'
000247 'Boss'
000247 'Szef'
000248 '~Import'
000248 '~Import'
000249 '~Language Change'
000249 'Zmien ~Jezyk'
000250 '~Font Palette'
000250 'Paleta ~Czcionek'
000251 'dummy'
000251 'pusty'
000252 'Select a new screen language'
000252 'Wybierz nowy jezyk ekranu'
000253 'Choose a font'
000253 'Wybierz czcionke'
000254 'Please select a clear text import file'
000254 'Podaj nazwe zbioru tekstu czytelnego'
000255 'Overwrite'
000255 'Nadpisac'
000256 'Try Again'
000256 'Jeszcze raz'
000257 ' exists - it will be overwritten!'
000257 ' istnieje - bedzie nadpisany!'
000258 'File Overwrite Warning'
000258 'Ostrzezenie nadpisania zboru'
000259 ''
000259 ''
000260 'Invalid password!'
000260 'Nielegalne haslo!'
000261 'Invalid Database Filename!'
000261 'Nielegalna nazwa zbioru bazy danych!'
000262 ' does not exist.'
000262 ' nie istnieje.'
000263 'Creating new database file.'
000263 'Tworzenie nowej bazy danych.'
000264 'Custom Fonts'
000264 'Czcionki niestandardowe'
000265 'Turns on drag/dropped fonts (slower startup)'
000265 'Wlacza przenosne czcionki (wolniejszy start)'
000266 'New password'
000266 'Nowe haslo'
000267 'Keyring/2 Password Editor'
000267 'Edytor hasel Keyring/2'
000268 'Save the new master password'
000268 'Zapisz nowe haslo glowne'
000269 '~Exit'
000269 '~Zakoncz'
000270 'Quit without saving the new master password'
000270 'Przerwij bez zapisywania hasla glownego'
000271 'Enter a new password for the current file'
000271 'Podaj nowe haslo dla biezacego zbioru'
000272 'Please retype the new master password *exactly*'
000272 'Powtorz nowe haslo glowne *dokladnie*'
000273 'New Master Password:'
000273 'Nowe haslo glowne:'
000274 'Verify Master Password:'
000274 'Potwierdz haslo glowne:'
000275 'Retry'
000275 'Ponow'
000276 'Password Verification Failure'
000276 'Blad potwierdzenia hasla'
000277 'Browser EXE'
000277 'EXE przegladarki'
000278 'List of Internet passwords'
000278 'Lista hasel Internetowych'
000279 'List of application passwords and registration codes'
000279 'Lista hasel i kodow rejestracyjnych aplikacji'
000280 'List of bank and credit card personal ID numbers'
000280 'Lista osobistych numerow indentyfikacyjnych bankowych i kart kredytowych'
000281 'List of safe and lock combinations'
000281 'Lista kombinacji sejfowych i zamkowych'
000282 'List of user specified secrets'
000282 'Lista sekretow uzytkownika'
000283 'List of user specified secrets'
000283 'Lista sekretow uzytkownika'
000284 'Current Expiration Date:'
000284 'Biezaca data waznosci:'
000285 'Use this page to quickly hide your secrets when someone walks in the room.'
000285 'Strona sluzaca do szybkiego ukrycia sekretow w przypadku czyjegos wejscia.'
000286 'New'
000286 'Nowy'
000287 'No expired records found!'
000287 'Nie znaleziono wygaslych zapisow!'
000288 'Expired Records'
000288 'Wygasle zapisy'
000289 'KeyRing/2 Expired Records'
000289 'Wygasle zapisy KeyRing/2'
000290 'Expired Passwords'
000290 'Wygasle hasla'
000291 'Double click on records to edit their expiration dates'
000291 'Podwojny klik na zapisach uruchamia edycje przeterminowania'
000292 ''
000292 ''
000293 'Password expiration date'
000293 'Data wygasniecia hasla'
000294 'zzzz'
000294 'zzzz'
000295 'Days to password expiration (warning only)'
000295 'Ilosc dni do wygasniecia hasla (ostrzezenie)'
000296 'Update password expiration date'
000296 'Uaktualnij date wygasniecia hasla'
000297 'Current Expiration Date'
000297 'Biezaca data wygasniecia'
000298 'Notebook Pg 6'
000298 'Str.6 notatnika'
000299 'Double click column names to edit them'
000299 'Kliknij podwojnie na kolumnie do edycji'
000300 'Click to move column name to left'
000300 'Kliknij aby przesunac nazwe kolumny w lewo'
000301 'Hide/Show this column name'
000301 'Chowaj/Pokaz nazwe tej kolumny'
000302 'Click to move selected column name to right'
000302 'Kliknij aby przesunac nazwe kolumny w prawo'
000303 'Notebook Pg 5'
000303 'Str.5 notatnika'
000304 'Notebook Pg 4'
000304 'Str.4 notatnika'
000305 'Notebook Pg 3'
000305 'Str.3 notatnika'
000306 'Notebook Pg 1'
000306 'Str.1 notatnika'
000307 'Click to move selected column name to left'
000307 'Kliknij aby przesunac nazwe wybranej kolumny w lewo'
000308 'Number of backup PWX files to keep'
000308 'Ilosc rezerwowych kopii zbioru PWX'
000309 'Backup Generations'
000309 'Generacje kopii rezerwowych'
000310 '~Use defaults'
000310 '~Uzyj standard'
000311 'Reset field and page names to defaults'
000311 'Ustaw domyslne nazwy pol i stron'
000312 'Enter the page name; Right click to change page hint'
000312 'Podaj nazwe strony; prawy klik zmienia wskazowke dla strony'
000313 'Notebook Pg 2'
000313 'Str.2 notatnika'
000314 'Password '
000314 'Haslo '
000315 'Icon '
000315 'Ikona '
000316 'Expiration Date '
000316 'Data waznosci '
000317 'Last Update '
000317 'Ostatnia zmiana '
000318 'URL '
000318 'URL '
000319 'Edit the Column Name'
000319 'Zmien nazwe kolumny'
000320 'Column Name'
000320 'Nazwa kolumny'
000321 'Hint for '
000321 'Wskazowka dla '
000322 'Hint'
000322 'Wskazowka'
000323 'Edit the column hint'
000323 'Edycja kolumny wskazowek'
000324 'Enter hint for page '
000324 'Podaj wskazowke dla strony '
000325 'Enable/Disable Multimedia Sound'
000325 'Wlacz/wylacz dzwiek multimedialny'
000326 'Enter a sound file to play at startup - right click for file dialog'
000326 'Podaj startowy zbior dzwiekowy - prawy klik dla dialogu zbioru'
000327 '~Revert to default'
000327 '~Powroc do standardu'
000328 'No item selected for reverting!'
000328 'No item selected for reverting!'   ?????
000329 'Database Expired!'
000329 'Przeterminowana baza danych!'
000330 '~Register'
000330 'Za~Rejestruj'
000331 'Enter your registration code and click this button'
000331 'Podaj swoj kod rejestracyjny i kliknij guzik'
000332 ''
000332 ''
000333 'KeyRing/2 v1.8'
000333 'KeyRing/2 v1.8'
000334 'Your name'
000334 'Nazwisko i Imie'
000335 'Your address (if supplied)'
000335 'Adres (o ile podany)'
000336 'Your city and state'
000336 'Miasto i Stan'
000337 'Your Zip/Postal Code and country'
000337 'Kod pocztowy i Kraj'
000338 'Your email address'
000338 'Adres pocztowy (e-mail)'
000339 'Your 16 character registration code'
000339 '16-znakowy kod rejestracyjny'
000340 'Nazwisko/Imie:'
000340 'Imie:'
000341 'Addr:'
000341 'Adres:'
000342 'City/State:'
000342 'Miasto/Stan:'
000343 'Zip/Country:'
000343 'Kod/Kraj:'
000344 'Email:'
000344 'Email:'
000345 'Reg Code:'
000345 'Kod Rej:'
000346 'Operational limits, if any'
000346 'Ewentualne ograniczenia'
000347 'Limits:'
000347 'Ograniczenia:'
000348 'Registered User'
000348 'Rejestrowany uzytkownik'
000349 'Company:'
000349 'Firma:'
000350 'Your company name'
000350 'Nazwa Firmy'
000351 'Demo Mode'
000351 'Tryb demonstracyjny'
000352 'Days to password expiration'
000352 'Dni do wygasniecia hasla'
000353 'Update password expiration date'
000353 'Zmien date wygasniecia hasla'
000354 ''
000354 ''
000355 'Help'
000355 'Pomoc'
000356 'Please enter your registration code (see README.REG)'
000356 'Podaj kod rejestracyjny (patrz: README.REG)'
000357 'RegCode'
000357 'KodRej.'
000358 'Error! Missing or invalid Registration Code'
000358 'Blad! brak lub nielegalny kod rejectracyjny'
000359 'Register ~Now!'
000359 'Zarejestruj ~Teraz!'
000360 'Sound'
000360 'Dzwiek'
000361 'Enable Multimedia Sounds'
000361 'Wlacz dzwiek multimedialny'
000362 'Play this file:'
000362 'Odegraj ten zbior:'
000363 'FldNameMenu'
000363 'MenuNazwZbi'
000364 'Select a multimedia file to play at startup'
000364 'Wybierz zbior dzwiekowy odtwarzany przy starcie'
000365 'Text'
000365 'Tekst'
000366 'This database file will expire in '
000366 'Waznosc bazy danych wygasnie za '
000367 ' days!'
000367 ' dni!'
000368 'KM000368'
000368 'KM000368'
000369 'KM000369'
000369 'KM000369'
000370 'KM000370'
000370 'KM000370'
000371 'KM000371'
000371 'KM000371'
000372 'KM000372'
000372 'KM000372'
000373 'KM000373'
000373 'KM000373'
000374 'KM000374'
000374 'KM000374'
000375 'KM000375'
000375 'KM000375'
000376 'KM000376'
000376 'KM000376'
000377 'KM000377'
000377 'KM000377'
000378 'KM000378'
000378 'KM000378'
000379 'KM000379'
000379 'KM000379'
000380 'KM000380'
000380 'KM000380'
000381 'KM000381'
000381 'KM000381'
000382 'KM000382'
000382 'KM000382'
000383 'KM000383'
000383 'KM000383'
000384 'KM000384'
000384 'KM000384'
000385 'KM000385'
000385 'KM000385'
000386 'KM000386'
000386 'KM000386'
000387 'KM000387'
000387 'KM000387'
000388 'KM000388'
000388 'KM000388'
000389 'KM000389'
000389 'KM000389'
000390 'KM000390'
000390 'KM000390'
000391 'KM000391'
000391 'KM000391'
000392 'KM000392'
000392 'KM000392'
000393 'KM000393'
000393 'KM000393'
000394 'KM000394'
000394 'KM000394'
000395 'KM000395'
000395 'KM000395'
000396 'KM000396'
000396 'KM000396'
000397 'KM000397'
000397 'KM000397'
000398 'KM000398'
000398 'KM000398'
000399 'KM000399'
000399 'KM000399'
000400 'KM000400'
000400 'KM000400'
000401 'KM000401'
000401 'KM000401'
000402 'KM000402'
000402 'KM000402'
000403 'KM000403'
000403 'KM000403'
000404 'KM000404'
000404 'KM000404'
000405 'KM000405'
000405 'KM000405'
:END OF FILE
