;-------------------------------;
; Copyright (C) 1999 IDK, Inc.  ;
;     http://www.idk-inc.com    ;
;   Virtual Language Msg File   ;
;   ~nokeywords~                ;
;-------------------------------;
000001 'Bent u er absoluut zeker van dat geen enkele van de wijzigingen moeten worden opgeslagen? (Indien er wijzigingen waren)?'
000002 'KeyRing/2'
000003 'Bewaar de wijzigingen in de database'
000004 'Hulp opvragen voorn KeyRing/2'
000005 'Het programma afsluiten'
000006 'Dit bepaald venster met de wachtwoorden verbergen'
000007 'Netscape openen met de geselecteerde locatie (URL)'
000008 'Instellingen van KeyRing/2 aanpassen'
000009 'Openen/wachtwoorden  database'
000010 '45'
000011 'Geen omzetten aan de gang.'
000012 '~Bestand'
000013 '~Openen'
000014 'Open een nieuwe database met wachtwoorden'
000015 '~Bewaren'
000016 'Bewaar de actieve database'
000017 'Bewaar a~ls'
000018 'Bewaar de actieve database onder een nieuwe naam'
000019 '~Instellingen'
000020 'Gegevensbestand als niet-versleuteld tekstbestand bewaren'
000021 '~Exporteren'
000022 'Af~drukken'
000023 'Alle gegevens en wachtwoorden afdrukken'
000024 '-'
000025 '~Afsluiten'
000026 'KeyRing/2 afsluiten'
000027 '~Hulp'
000028 'Hulp ~Index'
000029 'Inhoudstafel bekijken'
000030 'Al~gemene hulp'
000031 'Algemene  OS/2 hulp'
000032 '~Hoe de hulpbestanden gebruiken?'
000033 'Hoe de hulpbestanden gebruiken'
000034 '~Toetsenbord instellingen'
000035 'Hulp voor muis en sneltoetsen'
000036 'Key~ring2 Hulp'
000037 'Algemene KeyRing/2 hulp'
000038 'Over dit ~programma'
000039 'Over versie- en registratienummer'
000040 'Aftelmenu'
000041 'Aftellen stoppen'
000042 'Toepassingen: wachtwoorden en registratie coderingen'
000043 'Coderingen toepassingen'
000044 'Controleren op vervallen wachtwoorden'
000045 'Afteller'
000046 'Sorteermethode adressen wijzigen'
000047 '~Pictogrammen normaal'
000048 'Seleceer pictogrammen normaal'
000049 'Pictogrammen ~mini'
000050 'P~ictogrammen'
000051 'Toepassingscoderingen in Pictogrammen'
000052 '~Details'
000053 'Toepassingscoderingen in details'
000054 '~Niew'
000055 'Bewerken-aanhechten'
000056 'Bewerken(s)'
000057 '{Terugloop}'
000058 'Item bijvoegen'
000059 'Item(s) wissen'
000060 'Kopi‰er het wachtwoord naar het prikbord'
000061 'Locatie openen in  Netscape'
000062 '<Standaard>'
000063 'Wachtwoorden voor Weblocaties, Emailprogramma's en Internet aanbieders'
000064 'Internet wachtwoorden'
000065 'Pictogrambestand Kiezen'
000066 'Atteller'
000067 'PIN nummers van bank- en kredietkaarten'
000068 'PIN Nummers'
000069 'Selecteer ~Ingebouwd pictogram'
000070 'Combinaties voor sloten/kluizen'
000071 'Slotencombinaties'
000072 'Pictogrammen mini'
000073 'Eigen geheimpjes'
000074 'Gebruiker 1 coderingen'
000075 'Klik voor het aanmaken van een nieuwe kaart'
000076 'Andere wachtwoorden'
000077 'Gebruiker 2 coderingen'
000078 'Kan niet in het geheugen worden geladen:'
000079 'Foutje!'
000080 'Ok'
000081 'Er valt niets te wissen!'
000082 'Info'
000083 'Ja'
000084 'Neen'
000085 'Dit onderdeel wissen, zeker weten?'
000086 'Opgelet!'
000087 'Mogen dus zeker worden gewist, volgende '
000088 ' items?'
000089 'Er zijn hier geen locaties (URLs) beschikbaar!'
000090 'Er is geen locatie gekoppeld aan dit object!'
000091 'Er werd geen browser gedefini‰erd!'
000092 'Netscape liet het afweten!'
000093 'Foutje'
000094 'Wachtwoord is te kort!'
000095 'Tot weerziens'
000096 'Productregistratie vervallen!'
000097 'Foutje!'
000098 'Ongeldig wachtwoord'
000099 'Pictogram'
000100 'Beschrijving'
000101 'Gebruiker'
000102 'Wachtwoord'
000103 'S/N'
000104 'Jongste  bijwerking'
000105 'Vervaldatum'
000106 'Locatie'
000107 'Opmerking'
000108 'Door de gebruiker gestopt of wachtwoord zonder inhoud'
000109 'Bezig met afsluiten'
000110 'U moet eerst ŠŠn of meerdere objecten selecteren.'
000111 'Informatie'
000112 'Bewaar in KeyRing/2 *NIET* versleutelde database'
000113 'Er werd niets geselecteerd'
000114 'Er werd meer dan ŠŠn object geselecteerd'
000115 'Verbinden met '
000116 ' Mislukt!'
000117 'Verberg de kolom met wachtwoorden'
000118 'Toon de kolom met wachtwoorden'
000119 'Er werd meer dan een object geselecteerd'
000120 'Opgelet!'
000121 'Er werd niets geselecteerd'
000122 'KeyRing/2 Hoe registreren?'
000123 'Hoe registreren'
000124 '~Ok'
000125 'Klik om af te sluiten'
000126 'Vul uw voornaam in.  Tik op F1 voor hulp.'
000127 'Tik hier uw achternaam in'
000128 'Achternaam'
000129 'Voornaam'
000130 'Reg #'
000131 'Tik hier het registratienummer in'
000132 'Serie #'
000133 'Tik hier het serienummer in'
000134 ''
000135 ''
000136 'Geheim bewerken'
000137 'Geheime gegevens bewerken'
000138 'Bewaren'
000139 'Wijzigingen opslaan en terugkeren naar het hoofdscherm'
000140 'Neen, we stoppen ermee!'
000141 'Wijzigingen NIET opslaan'
000142 'Omschrijving van deze geheime informatie'
000143 'Omschrijving:'
000144 'Uw naam, schuilnaam, inlognaam, enz...'
000145 'Gebruikers ID:'
000146 'Serienummer, combinatie, PIN nummmer, enz...'
000147 'Serienummer:'
000148 'Wachtwoord voor deze toepassing, webpagina, login, enz ...'
000149 'Wachtwoord:'
000150 'Locatie:'
000151 'Locatie (URL) van dit geheim gegeven'
000152 'Opmerking in verband met dit geheim gegeven'
000153 'Opmerking:'
000154 'Dagen te gaan vooraleer het wachtwoord vervalt: (enkel een verwittiging)'
000155 'Dagen te gaan vooraleer het wachtwoord vervalt:'
000156 'Zie ik er niet fraai uit ?'
000157 'Zet hier een pictogram neer, of klik met de rechtemuisknop voor de instellingen op te roepen.'
000158 'EditRecMenu'
000159 'Een wachtwoord suggereren'
000160 'In kleine letters'
000161 'In hoofdletters'
000162 'In hoofd- en kleine letters'
000163 'Alfa'
000164 'Nummeriek'
000165 'Alfa-nummeriek'
000166 'Alfa-nummeriek + leestekens'
000167 'Pictogrammen'
000168 'Open het pictogrammenbestand'
000169 'Selecteer en ingebouwd pictogram'
000170 'Selecteer een pictogram voor dit object'
000171 'Geen vervaldatum'
000172 '~Ja'
000173 '~Nee'
000174 'Bent u er zeker van dat het huidig wachtwoord mag worden overschreven?'
000175 'KeyRing/2 aan het werk'
000176 'Versleutelen/ontsleutelen...'
000177 '1'
000178 'Aan het werk...'
000179 'KeyRing/2 Instellingen'
000180 'Tik pad-, bestandsnaam en de parameters van uw browser in.'
000181 'Netscape pad en locatie'
000182 'Zoeken'
000183 'Klik hier om bestandsnamen te zoeken/ingeven'
000184 'Beschrijving'
000185 'Verberg/toon de kolom met beschrijvingen'
000186 'Verberg/toon de kolom met pictogrammen'
000187 'Verberg/toon de kolom met wachtwoorden'
000188 'Gebruikers ID'
000189 'Verberg/toon de kolom met het gebruikers ID'
000190 'Verberg/toon de kolom met het serienummer'
000191 'Jongste bijwerking'
000192 'Verberg/toon de kolom met gegevens over het bijwerken'
000193 'Vervaldatum'
000194 'Verberg/toon de kolom met vervaldatums'
000195 'Verberg/toon de kolom met locaties (URL)'
000196 'Verberg/toon de kolom met opmerkingen'
000197 'Toepassingen'
000198 'WWW'
000199 'PIN'
000200 'Combinaties'
000201 'Andere - 1'
000202 'Andere - 2'
000203 'Sluiten'
000204 'Wijzigingen bewaren en er de brui aan geven'
000205 'Tantaluskwelling (niet geregistreerd product)'
000206 'Doe het ophouden!'
000207 'U kan het doen ophouden! Registreer, en dit scherm zal verdwijnen als sneeuw voor de zon!'
000208 '5'
000209 '~Hoe registreren?'
000210 'Pictogrammen voor Locaties (URL)Selectie'
000211 'Pictogrammen voor KeyRing/2'
000212 'Pictogrammen'
000213 'Kies een nieuw pictogram door het gewenste item te slepen.'
000214 'Sluiten'
000215 'KeyRing/2 aanmelding'
000216 'KeyRing/2 - Gelieve aan te melden'
000217 'Huidige database openen mbv het algemeen wachtwoord'
000218 'Annuleren'
000219 'KeyRing/2 afsluiten'
000220 'Vergendelingstype wordt hier weergegeven'
000221 'Het veilige wachtwoorden programma voor  OS/2'
000222 ''
000223 'Algemeen wachtwoord:'
000224 'Geef het Algemeen wachtwoord op (let op : kleine/hoofdletters)'
000225 'Tip:'
000226 'Tip om uzelf aan het wachtwoord te herinneren (hou dit goed verborgen voor buitenstaanders!)'
000227 'Huidig gegevensbestand - Klik rechts voor het bestandsvenster'
000228 'Huidig gegevensbestand:'
000229 'Selecteer een KeyRing/2 gegevensbestand'
000230 'Huidig gegevensbestand - Klik rechts voor bestandsvenster.'
000231 'KeyRing/2 - Opslaan Als'
000232 'Opslaan als bestand:'
000233 'Geef een nieuwe naam - Klik rechts voor bestandsvenster.'
000234 'Geef een nieuwe naam op voor het wachtwoordenbestand'
000235 'Beschrijving'
000236 'Wijziging'
000237 'Gebruiker'
000238 'S/N'
000239 'Wachtwoord'
000240 'Pictogram'
000241 'Internet'
000242 'Toepassingen'
000243 'PIN-codes'
000244 'Combinaties'
000245 'Gebruiker 1'
000246 'Gebruiker 2'
000247 'Beheerder'
000248 'I~mporteren'
000249 'Van ~taal veranderen'
000250 '~Lettertypenpalet'
000251 'domweg'
000252 'Een andere taal kiezen'
000253 'Lettertype wijzigen'
000254 'Gelieve een te importeren tekstbestand te selecteren'
000255 'Overschrijven'
000256 'Probeer opnieuw'
000257 ' bestaat reeds - wordt overschreven!'
000258 'Waarschuwing voor wanneer bestand wordt overschreven'
000259 ''
000260 'Ongeldig wachtwoord!'
000261 'Ongeldige bestandsnaam!'
000262 ' bestaat niet.'
000263 'Nieuw gegevensbestand aanmaken.'
000264 'Lettertypes'
000265 'Lettertypes aanpasbaar via slepen en neerzetten (trage bedoening!)'
000266 'Nieuw wachtwoord'
000267 'KeyRing/2 wachtwoordenbewerker'
000268 'Het nieuwe Algemeen wachtwoord opslaan'
000269 '~Afsluiten'
000270 'Afsluiten zonder het nieuwe Algemeen wachtwoord op te slaan'
000271 'Geef een nieuw wachtwoord op voor het huidige bestand'
000272 'Het nieuwe Algemeen wachtwoord *exact* herhalen'
000273 'Nieuw algemeen wachtwoord:'
000274 'Verifieer algemeen wachtwoord:'
000275 'Herhalen'
000276 'Foutieve wachtwoordverificatie'
000277 'Browser EXE'
000278 'Lijst met internet wachtwoorden'
000279 'Lijst met programmawachtwoorden, registratiecodes, ...'
000280 'Lijst met codes voor bankkaarten, kredietkaarten, ...'
000281 'Lijst met combinaties voor kluizen, sloten, ...'
000282 'Lijst met gebruikerspecifieke informatie'
000283 'Lijst met gebruikerspecifieke informatie'
000284 'Huidige Vervaldatum:'
000285 'Gebruik dit tabblad om snel uw geheimen te verbergen wanneer er zich onverwacht bezoek aanbiedt.'
000286 'Nieuw'
000287 'Geen vervallen gegevens voorhanden!'
000288 'Vervallen gegevens'
000289 'KeyRing/2 vervallen gegevens'
000290 'Vervallen wachtwoorden'
000291 'Dubbelklik op een object om de vervaldatum te wijzigen'
000292 ''
000293 'Vervaldatum wachtwoord'
000294 'zzzz'
000295 'Aantal dagen tot melding vervallen wachtwoord'
000296 'Vervaldatum wachtwoord wijzigen'
000297 'Huidige Vervaldatum'
000298 'Tabblad 6'
000299 'Dubbelklik om de kolomtitel te wijzigen'
000300 ''
000301 'Geselecteerde kolom verbergen/tonen'
000302 'Kolom naar rechts verplaatsen'
000303 'Tabblad 5'
000304 'Tabblad 4'
000305 'Tabblad 3'
000306 'Tabblad 1'
000307 'Kolom naar links verplaatsen'
000308 'Aantal te bewaren PWX backupbestanden'
000309 'Backup Generaties'
000310 '~Standaard'
000311 'Standaardbenaming voor velden en tabbladen herstellen'
000312 'Geef naam tabblad - Klik rechts om de tip te wijzigen'
000313 'Tabblad 2'
000314 'wachtwoord '
000315 'Pictogram '
000316 'Vervaldatum '
000317 'Laatste Wijziging '
000318 'URL '
000319 'Kolomtitel Wijzigen'
000320 'Kolomtitel'
000321 'Tip voor '
000322 'Tip'
000323 'Wijzig de tip i. v. m de kolom'
000324 'Geef een tip voor tabblad '
000325 'Multimedia Geluid Activeren/Desactiveren'
000326 'Geluidsbestand om bij opstart te spelen - Klik rechts voor bestandsvenster'
000327 '~Standaardinstelling terugzetten'
000328 'Geen item geselecteerd voor het terugzetten!'
000329 'Gegevensbestand vervallen!'
000330 '~Registreer'
000331 'Tik de registratiecode in en klik op deze knop'
000332 ''
000333 'KeyRing/2 v1.13'
000334 'Uw volledige naam'
000335 'Uw adres (indien dit werd opgegeven)'
000336 'Stad/gemeente'
000337 'Postcode en land'
000338 'Uw E-mailadres'
000339 'Uw registratiecode (16 karakters)'
000340 'Naam:'
000341 'Adres:'
000342 'Gemeente:'
000343 'Zip/Land:'
000344 'E-mail:'
000345 'Reg Code:'
000346 'Functionele beperkingen (indien aanwezig)'
000347 'Beperking:'
000348 'Geregistreerd Gebruiker'
000349 'Firma:'
000350 'De naam van uw firma'
000351 'Demo Modus'
000352 'Aantal dagen te gaan vooraleer het wachtwoord zal vervallen'
000353 'Vervaldatum wachtwoord wijzigen'
000354 ''
000355 'Help'
000356 'Gelieve uw registratiecode in te geven (zie README.REG)'
000357 'RegCode'
000358 'Fout! Ontbrekende of ongeldige Registratiecode'
000359 '~Nu registreren!'
000360 'Geluid'
000361 'Geluidjes actief'
000362 'Speel:'
000363 'FldNameMenu'
000364 'Kies een multimediabestand om te spelen bij opstart'
000365 'Tekst'
000366 'Dit kaartenbakbestand zal vervallen binnen '
000367 ' dagen!'
000368 'Gelieve voor PWC-bestanden de Importeer-functie te gebruiken'
000369 'Copyright (c) 1999-2000'
000370 'KeyRing/2 v1.13'
000371 'Aantal dagen te gaan vooraleer het wachtwoord zal vervallen'
000372 'Vervaldatum wachtwoord wijzigen'
000373 'Copyright 1999-2000, IDK, Inc.  kr2@idk-inc.com'
000374 'Opslaan Als afgebroken; Het oude wachtwoord en gegevensbestand blijven actief.'
000375 'U heeft het algemeen wachtwoord voor dit gegevensbestand gewijzigd!'
000376 'Kies Nieuw Wachtoord Gebruiken om het Algemeen Wachtwoord te wijzigen in wat zonet werd ingegeven.'
000377 'Kies Oud Wachtwoord Gebruiken om het oude wachtwoord opnieuw in te stellen'
000378 '~Nieuw wachtwoord Gebruiken'
000379 '~Oud wachtwoord gebruiken'
000380 'De encryptie module ontbreek!'
000381 'Indien u verder gaat, zullen al uw wachtwoorden open en bloot op de schijf worden bewaard en onbruikbaar worden na registratie van het volledige product.'
000382 'Zend een berichtje naar kr2@idk-inc.com om meer te vernemen over de encryptie module.'
000383 'Waarschuwing negeren.'
000384 'Opgelet! Waarschuwing! Opgelet!'
000385 'Wijzig de afkorting op de sorteerbalk voor '
000386 'Een afkorting kan maximaal 4 tekens groot zijn!'
000387 'KM000387'
000388 'Importeer een niet versleuteld tekstbestand als basis voor uw nieuw gegevensbestand.'
000389 'Verander de instellingen van KeyRing/2.'
000390 'Kopieer de gebruikersnaam naar het prikbord.'
000391 'Verplaats dit (deze) item(s) naar een andere pagina.'
000392 'Max revision'
000393 'KM000393'
000394 'KM000394'
000395 'KM000395'
000396 'KM000396'
000397 'KM000397'
000398 'KM000398'
000399 'KM000399'
000400 'KM000400'
000401 'KM000401'
000402 'KM000402'
000403 'KM000403'
000404 'KM000404'
000405 'KM000405'

