;-------------------------------;
; Copyright (C) 1999 IDK, Inc.  ;
;     http://www.idk-inc.com    ;
;   Virtual Language Msg File   ;
;   ~nokeywords~                ;
;-------------------------------;
000001 'Czy chcesz stracic wszystkie zmiany?'
000002 'KeyRing/2'
000003 'Zapisz zmiany bazy danych'
000004 'Pomoc o KeyRing/2'
000005 'Zakoncz KeyRing/2'
000006 'Ukryj kolumne hasel'
000007 'Wystartuj przegladarke za biezacym adresem URL'
000008 'Zmien ustawienia KeyRing/2'
000009 'Otworz/zbuduj baze danych hasel'
000010 '45'
000011 'Brak aktywnej konwersacji'
000012 '~Plik'
000013 '~Otworz'
000014 'Otworz nowa baze danych hasel'
000015 '~Zapisz'
000016 'Zapisz biezaca baze danych'
000017 'Z~apisz Jako'
000018 'Zapisz biezaca baze danych pod nowa nazwa'
000019 'Us~tawienia'
000020 'Zapisz baze danych jako zakodowany zbior tekstowy'
000021 '~Eksport'
000022 '~Drukuj'
000023 'drukuj wszystkie dokumenty bazy danych i hasla'
000024 '-'
000025 '~Koniec'
000026 'Zakoncz KeyRing/2'
000027 '~Pomoc'
000028 '~Index pomocy'
000029 'Spis tresci na temat KeyRing/2'
000030 'Pomoc ~Ogolna'
000031 'Ogolna pomoc o aplikacjach w OS/2'
000032 '~Uzywanie Pomocy'
000033 'Informacja jak uzywac systemu pomocy'
000034 'Pomoc o ~Klawiszach'
000035 'Pomoc o uzyciu myszy i klawiszy skrotowych'
000036 'Pomoc Key~ring2'
000037 'Ogolna pomoc o KeyRing/2'
000038 'Informacja o ~Produkcie'
000039 'Pokaz versje produktu i rejestracje'
000040 'MenuStopera'
000041 'Likwiduj Stoper'
000042 'Hasla aplikacji i kody rejestracyjne'
000043 'Kody aplikacji'
000044 'Wyszukaj przeterminowane hasla w bazie danych'
000045 'stoper'
000046 'Zmien kolejnosc sortowania adresow'
000047 '~Duze Ikony'
000048 'Zmien na duze ikony'
000049 '~Male Ikony'
000050 'Pokaz ~Ikony'
000051 'Pokaz kody aplikacji ikonograficznie'
000052 'Pokaz ~Szczegoly'
000053 'Pokaz kody aplikacji szczegolowo'
000054 '~Nowy'
000055 'AppEdit'
000056 'Edycja elementu(ow)'
000057 '{Enter}'
000058 'Dodaj Element'
000059 'Usun Element(y)'
000060 'Skopiuj haslo do schowka'
000061 'Wystartuj przegladarke na URL'
000062 '<domyslne>'
000063 'Hasla WWW, poczty i dostepu do Internetu (ISP)'
000064 'Hasla do Internetu'
000065 'Otworz ~Plik Ikon'
000066 'Stoper'
000067 'Numery bankowe i osobiste numery identyfikacyjne (PIN) kart kredytowych'
000068 'Numery (PIN)'
000069 'Wybierz Ikone ~Wewnetrzna'
000070 'Kombinacje sejfow i zamkow'
000071 'Kombinacje zamkow'
000072 'Zmien na male ikony'
000073 'Sekrety uzytkownika'
000074 'Kody uzytkownika'
000075 'Utworz nowy rekord'
000076 'Inne hasla'
000077 'Kody uzytkownika 2'
000078 'Blad ladowania okna:'
000079 'Blad!'
000080 'Ok'
000081 'Nie wybrano elementow do usuwania'
000082 'Info'
000083 'Tak'
000084 'Nie'
000085 'Czy usunac ten element'
000086 'Ostrzezenie'
000087 'Czy usunac te '
000088 ' elementy?'
000089 'Nie ma tu URL!'
000090 'Brak powiazania URL z tym elementem'
000091 'Brak definicji przegladarki'
000092 'Przegladarka nie wystartowala'
000093 'Blad'
000094 'Zbyt krotkie haslo!'
000095 'DoWidzenia'
000096 'Przeterminowany produkt!'
000097 'Blllaaadd!'
000098 'Nielegalne Haslo'
000099 'Ikona'
000100 'Opis'
000101 'Uzytkownik'
000102 'Haslo'
000103 'N/S'
000104 'Ostatnia zmiana'
000105 'Data Waznosci'
000106 'URL'
000107 'Notka'
000108 'Puste haslo lub polecenie konca pracy'
000109 'Konczenie pracy'
000110 'Wybierz conajmniej jeden element'
000111 'Informacja'
000112 'Zapisz *nie*zakodowana baze danych KR/2'
000113 'Nie wybrano elementow'
000114 'Wybrano wiecej niz jeden element'
000115 'Komunikacja z '
000116 ' zawiodla!'
000117 'Chowaj kolumne hasel'
000118 'Pokaz kolumne hasel'
000119 'Wybrano wiecej niz jeden element'
000120 'Ostrzezenie!'
000121 'Nie wybrano elementu'
000122 'O Produkcie/Rejestracja KeyRing/2'
000123 'O Produkccie/Rejestracja'
000124 '~Ok'
000125 'Kliknij aby skonczyc'
000126 'Podaj Imie. F1 wywola pomoc.'
000127 'Podaj nazwisko'
000128 'Nazwisko'
000129 'Imie'
000130 '# Rej'
000131 'Podaj rejestracyjny'
000132 '# seryjny'
000133 'Podaj numer seryjny'
000134 ''
000135 ''
000136 'Edycja sekretu'
000137 'Edycja zawartosci sekretu'
000138 'Zapisz'
000139 'Zapisz zmiany i wroc do programu glownego'
000140 'Anuluj'
000141 'Anuluj zmiany'
000142 'Opis tego sekretu'
000143 'Opis:'
000144 'Imie, pseudonim, identyfikator, itd'
000145 'ID uzytkownika:'
000146 'Numer seryjny, kombinacja, numer PIN, itd zwiazane z tym sekretem'
000147 'Numer seryjny:'
000148 'Haslo dla applikacji, strony WWW, login, itp.'
000149 'Haslo:'
000150 'URL:'
000151 'URL tego sekretu'
000152 'Notka tego sekretu'
000153 'Notka:'
000154 'Ilosc dni waznosci (dla ostrzezenia)'
000155 'Dni do ostrzezenia przeterminowania hasla:'
000156 'To ja jestem logo!'
000157 'Przenies tu ikone lub prawy klik'
000158 'MenuEdycElem'
000159 'Zasugeruj haslo'
000160 'Male litery'
000161 'Duze litery'
000162 'Mieszane litery'
000163 'Litery'
000164 'Cyfry'
000165 'Alfanumeryczne'
000166 'Alfanumeryczne i punktuacyjne'
000167 'MenuIkon'
000168 'Otworz zbior ikon'
000169 'Wybierz ikone wewnetrzna'
000170 'Wybierz ikone dla tego sekretu'
000171 'BezWaz'
000172 '~Tak'
000173 '~Nie'
000174 'Czy chcesz wymienic istniejace haslo?'
000175 'KeyRing/2 Pracuje'
000176 'Szyfrowanie/Deszyfrowanie...'
000177 '1'
000178 'Pracuje...'
000179 'Ustawienie KeyRing/2'
000180 'Wprowadz pelny adres programu przegladarki i parametry startu'
000181 'Adres przegladarki'
000182 'Szukaj'
000183 'Wywolaj dialog zbioru'
000184 'Opis'
000185 'Wlacz/wylacz kolumne opisu'
000186 'Wlacz/wylacz kolumne ikon'
000187 'Wlacz/wylacz kolumne hasel'
000188 'ID uzytkownika'
000189 'Wlacz/wylacz kolumne ID uzytkownika'
000190 'Wlacz/wylacz kolumne numerow seryjnych'
000191 'Ost Zm.'
000192 'Wlacz/wylacz kolumne ostatniej zmiany'
000193 'Data Waz'
000194 'Wlacz/wylacz kolumne daty waznosci'
000195 'Wlacz/wylacz kolumne URL'
000196 'Wlacz/wylacz kolumne notek'
000197 'Aplik'
000198 'WWW'
000199 'PIN'
000200 'Kombinacje'
000201 'Inne - 1'
000202 'Inne - 2'
000203 'Koniec'
000204 'Zapisz zmiany i zakoncz'
000205 'Przypomnienie o zarejestrowaniu programu'
000206 'Ach przestan!  Ach przestan!'
000207 'Mozesz:   zarejestrowac i przypomnienie zniknie!'
000208 '5'
000209 '~Jak zarejestrowac?'
000210 'Wybor ikony SiteMgr'
000211 'Wybor ikon KeyRing/2'
000212 'Ikony'
000213 'Przenies jedna z ikon w pole Edytora celem przydzielenia'
000214 'Zamknij'
000215 'Login Keyring/2'
000216 'KeyRing/2 - Zaloguj sie, prosze'
000217 'Otworz biezaca baze danych uzywajac glownego hasla'
000218 'Anuluj'
000219 'Przerwij KeyRing/2'
000220 'Tu bedzie typ szyfrowania'
000221 'Bezpieczne przechowywanie hasel dla OS/2'
000222 ''
000223 'Haslo Glowne:'
000224 'Podaj glowne haslo - male i duze litery rozrozniane'
000225 'Wskazowka:'
000226 'Wskazowka przypominajaca haslo glowne (niezbyt oczywista)'
000227 'Biezaca baza danych - prawy klik wywola menu'
000228 'Zbior biezacej bazy danych:'
000229 'Wybierz zbior bazy danych KeyRing/2'
000230 'Biezaca baza danych - prawy klik wywola menu.'
000231 'KeyRing/2 - Zapisz jako'
000232 'Zapisz jako zbior:'
000233 'Wybierz nowa nzawe; prawy klik wywola menu.'
000234 'Prosze podac a nowa nazwe zbioru bazy danych'
000235 'Opis"
000236 'Z-na'
000237 'Uzyt'
000238 'N/S'
000239 'Hasl'
000240 'Ikna'
000241 'Internet'
000242 'Applikacje'
000243 'PINy'
000244 'Kody zamkow'
000245 'Uzytk1'
000246 'Uzytk2'
000247 'Szef'
000248 '~Import'
000249 'Zmien ~Jezyk'
000250 'Paleta ~Czcionek'
000251 'pusty'
000252 'Wybierz nowy jezyk ekranu'
000253 'Wybierz czcionke'
000254 'Podaj nazwe zbioru tekstu czytelnego'
000255 'Nadpisac'
000256 'Jeszcze raz'
000257 ' istnieje - bedzie nadpisany!'
000258 'Ostrzezenie nadpisania zboru'
000259 ''
000260 'Nielegalne haslo!'
000261 'Nielegalna nazwa zbioru bazy danych!'
000262 ' nie istnieje.'
000263 'Tworzenie nowej bazy danych.'
000264 'Czcionki niestandardowe'
000265 'Wlacza przenosne czcionki (wolniejszy start)'
000266 'Nowe haslo'
000267 'Edytor hasel Keyring/2'
000268 'Zapisz nowe haslo glowne'
000269 '~Zakoncz'
000270 'Przerwij bez zapisywania hasla glownego'
000271 'Podaj nowe haslo dla biezacego zbioru'
000272 'Powtorz nowe haslo glowne *dokladnie*'
000273 'Nowe haslo glowne:'
000274 'Potwierdz haslo glowne:'
000275 'Ponow'
000276 'Blad potwierdzenia hasla'
000277 'EXE przegladarki'
000278 'Lista hasel Internetowych'
000279 'Lista hasel i kodow rejestracyjnych aplikacji'
000280 'Lista osobistych numerow indentyfikacyjnych bankowych i kart kredytowych'
000281 'Lista kombinacji sejfowych i zamkowych'
000282 'Lista sekretow uzytkownika'
000283 'Lista sekretow uzytkownika'
000284 'Biezaca data waznosci:'
000285 'Strona sluzaca do szybkiego ukrycia sekretow w przypadku czyjegos wejscia.'
000286 'Nowy'
000287 'Nie znaleziono wygaslych zapisow!'
000288 'Wygasle zapisy'
000289 'Wygasle zapisy KeyRing/2'
000290 'Wygasle hasla'
000291 'Podwojny klik na zapisach uruchamia edycje przeterminowania'
000292 ''
000293 'Data wygasniecia hasla'
000294 'zzzz'
000295 'Ilosc dni do wygasniecia hasla (ostrzezenie)'
000296 'Uaktualnij date wygasniecia hasla'
000297 'Biezaca data wygasniecia'
000298 'Str.6 notatnika'
000299 'Kliknij podwojnie na kolumnie do edycji'
000300 'Kliknij aby przesunac nazwe kolumny w lewo'
000301 'Chowaj/Pokaz nazwe tej kolumny'
000302 'Kliknij aby przesunac nazwe kolumny w prawo'
000303 'Str.5 notatnika'
000304 'Str.4 notatnika'
000305 'Str.3 notatnika'
000306 'Str.1 notatnika'
000307 'Kliknij aby przesunac nazwe wybranej kolumny w lewo'
000308 'Ilosc rezerwowych kopii zbioru PWX'
000309 'Generacje kopii rezerwowych'
000310 '~Uzyj standard'
000311 'Ustaw domyslne nazwy pol i stron'
000312 'Podaj nazwe strony; prawy klik zmienia wskazowke dla strony'
000313 'Str.2 notatnika'
000314 'Haslo '
000315 'Ikona '
000316 'Data waznosci '
000317 'Ostatnia zmiana '
000318 'URL '
000319 'Zmien nazwe kolumny'
000320 'Nazwa kolumny'
000321 'Wskazowka dla '
000322 'Wskazowka'
000323 'Edycja kolumny wskazowek'
000324 'Podaj wskazowke dla strony '
000325 'Wlacz/wylacz dzwiek multimedialny'
000326 'Podaj startowy zbior dzwiekowy - prawy klik dla dialogu zbioru'
000327 '~Powroc do standardu'
000328 'No item selected for reverting!'   ?????
000329 'Przeterminowana baza danych!'
000330 'Za~Rejestruj'
000331 'Podaj swoj kod rejestracyjny i kliknij guzik'
000332 ''
000333 'KeyRing/2 v1.8'
000334 'Nazwisko i Imie'
000335 'Adres (o ile podany)'
000336 'Miasto i Stan'
000337 'Kod pocztowy i Kraj'
000338 'Adres pocztowy (e-mail)'
000339 '16-znakowy kod rejestracyjny'
000340 'Imie:'
000341 'Adres:'
000342 'Miasto/Stan:'
000343 'Kod/Kraj:'
000344 'Email:'
000345 'Kod Rej:'
000346 'Ewentualne ograniczenia'
000347 'Ograniczenia:'
000348 'Rejestrowany uzytkownik'
000349 'Firma:'
000350 'Nazwa Firmy'
000351 'Tryb demonstracyjny'
000352 'Dni do wygasniecia hasla'
000353 'Zmien date wygasniecia hasla'
000354 ''
000355 'Pomoc'
000356 'Podaj kod rejestracyjny (patrz: README.REG)'
000357 'KodRej.'
000358 'Blad! brak lub nielegalny kod rejectracyjny'
000359 'Zarejestruj ~Teraz!'
000360 'Dzwiek'
000361 'Wlacz dzwiek multimedialny'
000362 'Odegraj ten zbior:'
000363 'MenuNazwZbi'
000364 'Wybierz zbior dzwiekowy odtwarzany przy starcie'
000365 'Tekst'
000366 'Waznosc bazy danych wygasnie za '
000367 ' dni!'
000368 'KM000368'
000369 'KM000369'
000370 'KM000370'
000371 'KM000371'
000372 'KM000372'
000373 'KM000373'
000374 'KM000374'
000375 'KM000375'
000376 'KM000376'
000377 'KM000377'
000378 'KM000378'
000379 'KM000379'
000380 'KM000380'
000381 'KM000381'
000382 'KM000382'
000383 'KM000383'
000384 'KM000384'
000385 'KM000385'
000386 'KM000386'
000387 'KM000387'
000388 'KM000388'
000389 'KM000389'
000390 'Copy Username to Clipboard'
000391 'KM000391'
000392 'KM000392'
000393 'KM000393'
000394 'KM000394'
000395 'KM000395'
000396 'KM000396'
000397 'KM000397'
000398 'KM000398'
000399 'KM000399'
000400 'KM000400'
000401 'KM000401'
000402 'KM000402'
000403 'KM000403'
000404 'KM000404'
000405 'KM000405'
