{$I-,V-,S-,R-,F-,B-}

{*********************************************************}
{*                   FBDEMO.PAS 5.50                     *}
{*     Copyright (c) TurboPower Software 1990, 1994.     *}
{*                 All rights reserved.                  *}
{*********************************************************}

program FbDemo;
  {-Demonstrates how to use FBrowse unit}
uses
  FbdMain;
begin
  FBDemoMain;
end.
