{***************************************************************************
* Filename: ~modname~
* Version:  ~version~
* Date:     ~date~ @ ~time~
* Group:    ~group~
* Release:  ~release~
* ----------------------------
*
* Modifications
* -------------
*
* Version   Date     Time    Programmer   Description
* ~log~
*
*
* ~notes~
* Description
* -----------
*
*
*
* ~notesend~
* ~nokeywords~
*
****************************************************************************
}
{$O-}
{ Accompaniment to USpxGlo. Data that must be referenced before the }
{ overlay manager loads should reside here.                         }

Unit USpxDat;

interface

Const
  ThisIsMachineControlSlave : boolean = False;
  SlaveNumber : word = 0;

implementation

End.
